<?php
define("BDS","./bds/");
define("CONFIG","./config/");
define("CONTROLLERS","./controllers/");
define("CORE","../core/");
define("INSTASCAN","./core/instascan-js/");
define("JQUERY","./core/Jquery/");
define("AUDIO","./audio/");
define("GENERALFUNC","../general_functions/");
define("DOCUMENTS","./documents/");
define("FILES","./files/");
define("FONTS","./fonts/");
define("IMGS","./imgs/");
define("MODELS","../models/");
define("VIEWS","./views/");
define("POPS","./views/pops/");
define("CSS","./views/css/");
define("JS","./views/js/");
define("TP","./views/parts_technical_panel/");
define("TPJS","./views/parts_technical_panel/js/");
define("TPF","./views/parts_technical_panel/parts_forms/");
define("TPAJAX","./views/parts_technical_panel/js/ajax/");
define("AJAX","./views/js/ajax/");
?>
