<script type="text/javascript" src="<?php echo TPJS;?>screen_charge.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>keypress.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>generals_functions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>change_sections.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>open_close_aside_menu.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>resize_change.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>providers_tabs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>products_tabs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>clean_inputs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>length_data_for_pages.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>ba_buttons_pagination_product.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>ba_buttons_pagination_provider.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>display_info_actions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>asycronic_function.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_info_tab_product.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_reports_technicals.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_save_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_setting.js"></script>
