<script type="text/javascript" src="<?php echo TPJS;?>seach_updates.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>screen_charge.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>keypress.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>generals_functions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>change_sections.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>open_close_aside_menu.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>resize_change.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>clients_tabs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>set_address_client.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>delete_address_client.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>clean_inputs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>view_hidde_elements.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>return_to_new_client.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_search_reports_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_search_clients_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>length_data_for_pages.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>ba_buttons_pagination.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>ba_buttons_pagination_client.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>edit_client_info.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>display_info_actions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>asycronic_function.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_reports.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_client.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_new_client.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_update_client.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_update_state_client.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_change_city.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_save_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_setting.js"></script>
