<script type="text/javascript" src="<?php echo TPJS;?>save_and_recovery_info_functions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>screen_charge.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>keypress.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>generals_functions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>change_sections.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>open_close_aside_menu.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>resize_change.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>open_pop_qr_search.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>reports_tabs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>file_selector.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>clean_inputs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>draw_canvas_client_full.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>draw_canvas_technical_full.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>open_close_pops_firms.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_search_machine_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>length_data_for_pages.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>ba_buttons_pagination_machine.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>read_QR.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>display_info_actions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>asycronic_function.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_client.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_info_bussines.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_put_parts_address.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_fill_client_info.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_record_reports.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_machine.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_save_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_setting.js"></script>
