<script type="text/javascript" src="<?php echo TPJS;?>seach_updates.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>screen_charge.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>keypress.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>generals_functions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>change_sections.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>open_close_aside_menu.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>resize_change.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>reports_tabs.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>close_pop_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>close_pop_change_state_user.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>close_pop_restart_user.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>show_hidde_new_user_select.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>clean_files_new_user.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>length_data_for_pages.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>ba_buttons_pagination_user.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>sort_search_users_table.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>display_info_actions.js"></script>
<script type="text/javascript" src="<?php echo TPJS;?>asycronic_function.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_update_state_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_restart_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_search_btns_results_users.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_new_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_save_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_record_user.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_setting.js"></script>
<script type="text/javascript" src="<?php echo TPAJAX;?>ajax_map_location.js"></script>
